
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/ui/globals.css'
import SideNav from './ui/navigation/sidenav'
import { TopNavbar } from './ui/navigation/TopNavBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 /* return (
    <html lang="en">
      <body className={inter.className}>
          <div className="flex h-screen flex-row md:flex-row md:overflow-hidden">
              <TopNavbar/>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
              <SideNav />
            </div>
            <div className="flex-grow py-5 md:overflow-y-auto">{children}</div>
          </div>
          </div>
      </body>
    </html>
  )*/

  return (
    <html lang="en" >
      <body className={inter.className}>
          <TopNavbar/>
          {children}
      </body>
    </html>
  )
}
